anguage: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t rsivanandan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rsivanandan/docker-react npm run test
